create or replace schema LDA.RAW_LD;

create or replace TABLE RAW_ASSETS (
	ID NUMBER(38,0) NOT NULL,
	ASSET_TYPE_ID NUMBER(38,0),
	CLIENT_GROUP_ID NUMBER(38,0),
	NAME VARCHAR(255),
	SECURITY NUMBER(38,0) NOT NULL DEFAULT 0,
	JOINTLY_OWNED NUMBER(38,0) DEFAULT 0,
	INDEPENDENT_VALUATION FLOAT,
	INTERNAL_VALUATION FLOAT,
	ASSET_DESCRIPTION VARCHAR(16777216),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	ASSET_ADDRESS_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	USE_TYPE_ID NUMBER(38,0),
	INSURANCE_EXPIRY_DATE TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ASSET_ADDRESSES (
	ID NUMBER(38,0) NOT NULL,
	POSTCODE VARCHAR(255),
	COUNTRY VARCHAR(255),
	COUNTY VARCHAR(255),
	CITY VARCHAR(255),
	DISTRICT VARCHAR(255),
	STREET VARCHAR(255),
	HOUSE_NUMBER VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ASSET_CLIENT_COMPANIES (
	ID NUMBER(38,0) NOT NULL,
	ASSET_ID NUMBER(38,0),
	CLIENT_COMPANIES_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ASSET_CLIENT_INDIVIDUALS (
	ID NUMBER(38,0) NOT NULL,
	ASSET_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ASSET_INSURANCES (
	ID NUMBER(38,0) NOT NULL,
	ASSET_ID NUMBER(38,0),
	POLICY_NUMBER VARCHAR(255),
	IS_NOVELLUS_NOMINATED_PAYEE NUMBER(38,0) NOT NULL,
	TYPE_LOSS_PAYEE VARCHAR(30),
	EXPIRY_DATE DATE NOT NULL,
	SUM_INSURED NUMBER(15,2) NOT NULL,
	TITLE_INSURANCE NUMBER(38,0) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ASSET_INSURANCE_NOTES (
	ID NUMBER(38,0) NOT NULL,
	ASSET_INSURANCE_ID NUMBER(38,0),
	NOTE_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ASSET_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	MAX_LTV FLOAT,
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ATTRIBUTES (
	ID NUMBER(38,0) NOT NULL,
	PARENT_ID VARCHAR(255),
	ATTRIBUTE_BATCH VARCHAR(255) DEFAULT '0',
	ATTRIBUTE_GROUP_ID NUMBER(38,0),
	ATTRIBUTE_TYPE_ID NUMBER(38,0),
	REFERENCE VARCHAR(255),
	IS_SYSTEM_ATTRIBUTE NUMBER(38,0) NOT NULL DEFAULT 0,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	FIELD_NAME VARCHAR(255),
	primary key (ID)
);
create or replace TABLE RAW_ATTRIBUTE_ENTITIES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CLASS VARCHAR(64),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ATTRIBUTE_GROUPS (
	ID NUMBER(38,0) NOT NULL,
	ATTRIBUTE_ENTITY_ID NUMBER(38,0),
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ATTRIBUTE_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	IS_SYSTEM_TYPE NUMBER(38,0) NOT NULL DEFAULT 1,
	primary key (ID)
);
create or replace TABLE RAW_ATTRIBUTE_VALUES (
	ID NUMBER(38,0) NOT NULL,
	CLIENT_FORM_ID NUMBER(38,0),
	ATTRIBUTE_ID NUMBER(38,0),
	VALUE VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_AUDIT (
	ID NUMBER(38,0) NOT NULL,
	USER_ID NUMBER(38,0),
	MODEL VARCHAR(255),
	MODEL_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	EVENT_GROUP_ID VARCHAR(255),
	EVENT_TYPE VARCHAR(255),
	RECORD_CREATED NUMBER(38,0),
	FIELD VARCHAR(255),
	FIELD_NAME VARCHAR(255),
	FROM_DATA VARCHAR(255),
	FROM_DATA_TEXT VARCHAR(255),
	TO_DATA VARCHAR(255),
	TO_DATA_TEXT VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_BANK_DETAILS (
	ID NUMBER(38,0) NOT NULL,
	SORT_CODE VARCHAR(255),
	ACCOUNT_NUMBER VARCHAR(255),
	BIC VARCHAR(255),
	IBAN VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_BORROWERS (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	CLIENT_COMPANY_ID NUMBER(38,0),
	CLIENT_GROUP_ID NUMBER(38,0),
	MAIN_CONTACT NUMBER(38,0) NOT NULL DEFAULT 0,
	ADMINISTRATOR NUMBER(38,0) NOT NULL DEFAULT 0,
	GUARANTOR NUMBER(38,0) NOT NULL DEFAULT 0,
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_BROKERS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(255),
	COMMISSION_RATE FLOAT NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	ENGAGEMENT_LETTER DATE,
	ADDRESS_ID NUMBER(38,0),
	LANDLINE VARCHAR(255),
	MOBILE VARCHAR(255),
	BANK_DETAILS VARCHAR(16777216),
	LOCATION VARCHAR(16777216),
	SECONDARY_PHONE VARCHAR(255),
	primary key (ID)
);
create or replace TABLE RAW_BROKER_AGENTS (
	ID NUMBER(38,0) NOT NULL,
	BROKER_ID NUMBER(38,0),
	USER_ID NUMBER(38,0),
	NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(255),
	BANK_DETAILS_ID NUMBER(38,0),
	QUESTIONABLE NUMBER(38,0) NOT NULL DEFAULT 0,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	ADDRESS_ID NUMBER(38,0),
	LANDLINE VARCHAR(255),
	MOBILE VARCHAR(255),
	primary key (ID)
);
create or replace TABLE RAW_BROKER_AGENT_DEALS (
	ID NUMBER(38,0) NOT NULL,
	BROKER_AGENT_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_BROKER_AGENT_NOTES (
	ID NUMBER(38,0) NOT NULL,
	BROKER_AGENT_ID NUMBER(38,0),
	NOTE_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	NEGATIVE_RELATIONSHIP NUMBER(38,0) DEFAULT 0,
	primary key (ID)
);
create or replace TABLE RAW_BROKER_NOTES (
	ID NUMBER(38,0) NOT NULL,
	BROKER_ID NUMBER(38,0),
	NOTE_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CCR_REPORTS (
	ID NUMBER(38,0) NOT NULL,
	TITLE VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	FILE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CHARGES (
	ID NUMBER(38,0) NOT NULL,
	PARENT_ID NUMBER(38,0),
	CHARGE FLOAT NOT NULL,
	DATE DATE NOT NULL,
	NOTE VARCHAR(16777216),
	REMOVED NUMBER(38,0) NOT NULL DEFAULT 0,
	ASSET_ID NUMBER(38,0),
	LENDER_ID NUMBER(38,0),
	CHARGE_TYPE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CHARGE_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_ADDRESSES (
	ID NUMBER(38,0) NOT NULL,
	OWNERSHIP_TYPE_ID NUMBER(38,0),
	POSTCODE VARCHAR(255),
	COUNTRY VARCHAR(255),
	COUNTY VARCHAR(255),
	CITY VARCHAR(255),
	DISTRICT VARCHAR(255),
	STREET VARCHAR(255),
	HOUSE_NUMBER VARCHAR(255),
	LIVED_FOR_MONTHS NUMBER(38,0),
	LIVED_FOR_YEARS NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_COMPANIES (
	ID NUMBER(38,0) NOT NULL,
	COMPANY_ID NUMBER(38,0),
	NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	ADDRESS_ID NUMBER(38,0),
	LANDLINE VARCHAR(255),
	MOBILE VARCHAR(255),
	BANK_DETAILS VARCHAR(16777216),
	BANK_DETAILS_ID NUMBER(38,0),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_COMPANY_CLIENTS (
	ID NUMBER(38,0) NOT NULL,
	CLIENT_COMPANY_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	SHAREHOLDING_PERCENTAGE FLOAT NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_COMPANY_NOTES (
	ID NUMBER(38,0) NOT NULL,
	CLIENT_COMPANY_ID NUMBER(38,0),
	NOTE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_FORMS (
	ID NUMBER(38,0) NOT NULL,
	CLIENT_FORM_HASH VARCHAR(255),
	FORM_ID NUMBER(38,0),
	CLIENT_FORM_BATCH_ID VARCHAR(255),
	PAID NUMBER(38,0) NOT NULL DEFAULT 0,
	DEAL_ID NUMBER(38,0),
	BROKER_AGENT_ID NUMBER(38,0),
	MAIN_RECIPIENT NUMBER(38,0) NOT NULL DEFAULT 0,
	CLIENT_ID NUMBER(38,0),
	CLIENT_COMPANY_ID NUMBER(38,0),
	CLIENT_GROUP_ID NUMBER(38,0),
	FORM_DATA_JSON VARCHAR(16777215),
	SENT_BY_USER_ID NUMBER(38,0),
	FORM_SENT_AT TIMESTAMP_NTZ(9),
	FORM_POPULATED_AT TIMESTAMP_NTZ(9),
	FORM_COMPLETED_AT TIMESTAMP_NTZ(9),
	DOCUSIGN_DOCUMENT_SENT NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	CLIENT_FORM_STATUS_ID NUMBER(38,0),
	DOCUSIGN_ENVELOPE_ID VARCHAR(255),
	DOCUSIGN_COMPLETED_DATETIME DATE,
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_FORM_ATTACHMENTS (
	ID NUMBER(38,0) NOT NULL,
	CLIENT_FORM_ID NUMBER(38,0),
	FILE_ID NUMBER(38,0),
	FORM_ATTRIBUTE_REFERENCE VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_FORM_STATUS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_GROUPS (
	ID NUMBER(38,0) NOT NULL,
	COMPANY_ID NUMBER(38,0),
	NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	LANDLINE VARCHAR(255),
	MOBILE VARCHAR(255),
	BANK_DETAILS VARCHAR(16777216),
	ADDRESS_ID NUMBER(38,0),
	BANK_DETAILS_ID NUMBER(38,0),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_GROUP_CLIENTS (
	ID NUMBER(38,0) NOT NULL,
	CLIENT_GROUP_ID NUMBER(38,0),
	CLIENT_COMPANY_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	GROUP_LEADER NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_INDIVIDUALS (
	ID NUMBER(38,0) NOT NULL,
	ADDRESS_ID NUMBER(38,0),
	PREVIOUS_ADDRESS_ID NUMBER(38,0),
	USER_ID NUMBER(38,0),
	PERMANENT_UK_RESIDENT NUMBER(38,0) NOT NULL DEFAULT 1,
	NAME_TITLE_ID NUMBER(38,0),
	MARITAL_STATUS_ID NUMBER(38,0),
	TOTAL_GROSS_INCOME FLOAT,
	EMPLOYMENT_STATUS VARCHAR(255),
	RESIDENCY_STATUS VARCHAR(255),
	JOB_TITLE VARCHAR(255),
	NATURE_OF_BUSINESS VARCHAR(255),
	EMPLOYER_NAME VARCHAR(255),
	PASSPORT_NUMBER VARCHAR(255),
	IS_ADMINISTRATOR_ONLY NUMBER(38,0) NOT NULL DEFAULT 0,
	DOB_DAY VARCHAR(255),
	DOB_MONTH VARCHAR(255),
	DOB_YEAR VARCHAR(255),
	PREVIOUS_NAMES VARCHAR(255),
	NATIONALITY VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CLIENT_INDIVIDUAL_NOTES (
	ID NUMBER(38,0) NOT NULL,
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	NOTE_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_COMPANIES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_CURRENCIES (
	ID NUMBER(38,0) NOT NULL,
	LABEL VARCHAR(255),
	CURRENCY_CODE VARCHAR(255),
	PREFIX VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEALS (
	ID NUMBER(38,0) NOT NULL,
	PARENT_ID NUMBER(38,0),
	CASE_OWNER_ID NUMBER(38,0),
	REFERENCE VARCHAR(255),
	TYPE_ID NUMBER(38,0),
	GUARANTOR_ID NUMBER(38,0),
	CLIENT_GROUP_ID NUMBER(38,0),
	CURRENCY_ID NUMBER(38,0),
	STATUS_ID NUMBER(38,0),
	APPROVAL_REQUESTED_BY NUMBER(38,0),
	APPROVED_BY NUMBER(38,0),
	DATE_OF_APPROVAL_REQUIRED DATE,
	DATE_OF_APPROVAL DATE,
	PURPOSE_CREDIT_TYPE_ID NUMBER(38,0),
	BASE_RATE_FLOOR FLOAT,
	LOAN_TERM VARCHAR(255),
	PURCHASE_PRICE FLOAT,
	AMOUNT_REQUIRED VARCHAR(255),
	MAX_LTV NUMBER(38,0),
	MARKETING_SOURCE_ID NUMBER(38,0),
	USAGE_DETAILS VARCHAR(16777216),
	UNDERVALUE_DETAILS VARCHAR(16777216),
	FUNDS_GOING_TO_BE_USED_FOR VARCHAR(16777216),
	SHORTFALL_BALANCE_DETAILS VARCHAR(16777216),
	EXIT_STRATEGY VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	MARKETING_SOURCE_UTM VARCHAR(255),
	MARKETING_CAMPAIGN_UTM VARCHAR(255),
	ABORTED_REASON_ID NUMBER(38,0),
	PREVIOUS_STATUS_ID NUMBER(38,0),
	ESTIMATED_SALE_TIME DATE,
	ESTIMATED_CONSTRUCTION_TIME DATE,
	SQUARE_FOOTAGE NUMBER(38,0),
	PRICE_PER_SQUARE_FOOT NUMBER(8,2),
	PRIVATE_INVESTOR NUMBER(38,0) NOT NULL DEFAULT 0,
	primary key (ID)
);
create or replace TABLE RAW_DEAL_ABORTED_REASONS (
	ID NUMBER(38,0) NOT NULL,
	TITLE VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_ACTIVITIES (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	NOTE VARCHAR(16777216),
	USER_ID NUMBER(38,0),
	AUDIT_ID NUMBER(38,0),
	FILE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DATE DATE NOT NULL,
	TIME_TAKEN TIME(9) NOT NULL,
	primary key (ID)
);
create or replace TABLE RAW_DEAL_DOCUMENTS (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	FILE_ID NUMBER(38,0),
	DEAL_DOCUMENT_CATEGORY_ID NUMBER(38,0),
	BORROWER_ID NUMBER(38,0),
	CLIENT_COMPANY_ID NUMBER(38,0),
	DEAL_DOCUMENT_RISK_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	ASSET_ID NUMBER(38,0),
	DESCRIPTION VARCHAR(16777216),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_DOCUMENT_CATEGORIES (
	ID NUMBER(38,0) NOT NULL,
	SHAREPOINT_UNIQUE_ID VARCHAR(1024),
	FOLDER_PATH VARCHAR(1024),
	PARENT_ID NUMBER(38,0),
	NAME VARCHAR(255),
	FILE_COUNT NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	SIZE NUMBER(38,0),
	LAST_UPDATED TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_DOCUMENT_CATEGORIES_DATA (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	DEAL_DOCUMENT_CATEGORY_ID NUMBER(38,0),
	FILE_COUNT NUMBER(38,0),
	SIZE NUMBER(38,0),
	LAST_UPDATED TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_DOCUMENT_RISK (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_INTRODUCERS (
	ID NUMBER(38,0) NOT NULL,
	INTRODUCER_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	BROKER_ID NUMBER(38,0),
	INTRODUCER_TYPE_ID NUMBER(38,0),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_NOTES (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	REPLIED_TO_ID NUMBER(38,0),
	CREATED_BY_USER_ID NUMBER(38,0),
	IMPORTANT NUMBER(38,0) NOT NULL DEFAULT 0,
	NOTE VARCHAR(16777216),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_NOTIFICATION_RULES (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	DRAWDOWN_EVENT_TYPE_ID NUMBER(38,0),
	FILE_ID NUMBER(38,0),
	NOTIFICATION_RULE_ID NUMBER(38,0),
	SCHEDULED_FOR NUMBER(38,0),
	INTERVAL_TYPE VARCHAR(255),
	SUBJECT VARCHAR(255),
	BODY VARCHAR(16777216),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	SCHEDULED_DATE DATE,
	NOTIFICATION_TEMPLATE_ID NUMBER(38,0),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_NOTIFICATION_RULES_RECIPIENTS (
	ID NUMBER(38,0) NOT NULL,
	DEAL_NOTIFICATION_RULE_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_RATE_FLOORS (
	ID NUMBER(38,0) NOT NULL,
	VARIABLE_SOURCE_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	FLOOR_RATE FLOAT NOT NULL,
	primary key (ID)
);
create or replace TABLE RAW_DEAL_SETTINGS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	STATUS NUMBER(38,0) NOT NULL DEFAULT 0,
	ORDER_ID NUMBER(38,0),
	DEAL_SETTING_GROUP_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_SETTING_GROUPS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	ORDER_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_STATUSES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_TASK (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	COMPLETE NUMBER(38,0) NOT NULL DEFAULT 0,
	ORDER_ID NUMBER(38,0),
	DEAL_TASK_GROUP_ID NUMBER(38,0),
	ACTIONED_BY_USER_ID NUMBER(38,0),
	ASSIGNED_TO_USER_ID NUMBER(38,0),
	DATE_DUE DATE,
	DATE TIMESTAMP_NTZ(9),
	AUTO_ASSIGN_TO_CASE_OWNER NUMBER(38,0) NOT NULL DEFAULT 0,
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_TASK_GROUP (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	ORDER_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DEAL_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DELEGATED_OWNERS (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	USER_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DOCUMENTS (
	ID NUMBER(38,0) NOT NULL,
	FILENAME VARCHAR(255),
	DOCUMENT_TYPE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DOCUMENT_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DRAWDOWNS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DEAL_ID NUMBER(38,0),
	DRAWDOWN_STATUS_ID NUMBER(38,0),
	LENDER_ID NUMBER(38,0),
	INTEREST_RATE FLOAT,
	REDEMPTION_DATE DATE,
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	INTEREST_CALCULATION_TYPE_ID NUMBER(38,0),
	TOTAL_NET_LOAN FLOAT,
	GROSS_LOAN FLOAT,
	TERM_MONTHS NUMBER(38,0),
	TERM_DAYS NUMBER(38,0),
	MONTHLY_RATE FLOAT,
	DAILY_RATE FLOAT,
	LOAN_START_DATE DATE,
	REFINANCED_DATE DATE,
	REFINANCE_GROSS_AMOUNT FLOAT,
	REFINANCED_FROM_ID NUMBER(38,0),
	REFINANCED_TO_ID NUMBER(38,0),
	LOAN_ADMINISTRATION_START_DATE DATE,
	LOAN_END_DATE DATE,
	DEAL_TYPE_ID NUMBER(38,0),
	INTEREST_TYPE_ID NUMBER(38,0),
	MAX_LOAN_AMOUNT FLOAT,
	LTV FLOAT,
	INTEREST_PAYMENT FLOAT,
	ACTUAL_ACCRUED_INTEREST_PAYMENT FLOAT,
	MONTHLY_INTEREST FLOAT,
	DAILY_INTEREST FLOAT,
	TOTAL_NET_ADVANCE FLOAT,
	TOTAL_INVESTMENT FLOAT,
	ESTIMATED_RETURN FLOAT,
	ESTIMATED_MARGIN FLOAT,
	REDEMPTION_VALUE FLOAT,
	LOAN_CALCULATION_METHOD_ID NUMBER(38,0),
	ASSET_VALUE FLOAT,
	ASSET_TYPE_ID NUMBER(38,0),
	MAX_LTV FLOAT,
	LTV_OVERRIDE_REASON VARCHAR(16777216),
	VARIABLE_RATE_SOURCE_ID NUMBER(38,0),
	SOURCE_RATE FLOAT,
	MARGIN FLOAT,
	VARIABLE_RATE_ID NUMBER(38,0),
	TOTAL_FEES FLOAT,
	TOTAL_INTEREST_ON_FEES FLOAT,
	REDEEM_DATE DATE,
	EXIT_FEE_CALCULATED FLOAT,
	FUNDER_INTEREST_RATE FLOAT,
	HYBRID_PARENT_ID NUMBER(38,0),
	IS_HYBRID_PARENT NUMBER(38,0) NOT NULL DEFAULT 0,
	EXIT_STRATEGIES VARCHAR(16777215),
	MARKETING_CHANNEL_ID NUMBER(38,0),
	DEFAULT_RATE FLOAT,
	YEAR_TYPE NUMBER(38,0) DEFAULT 0,
	MONTHLY_COMPOUND NUMBER(38,0) DEFAULT 0,
	QUARTERLY_COMPOUND NUMBER(38,0) DEFAULT 0,
	COMPOUND_DAY NUMBER(38,0) DEFAULT 1,
	FUNDER_ARRANGEMENT_FEE NUMBER(10,2) NOT NULL DEFAULT 0,
	FUNDER_ARRANGEMENT_FEE_IS_PERCENT NUMBER(38,0) NOT NULL DEFAULT 0,
	NOTICE_PERIOD_DAYS NUMBER(38,0),
	ADDITIONAL_INTEREST_RATE FLOAT DEFAULT 0,
	EXTENDED_FROM NUMBER(38,0),
	EXTENSION_DATE DATE,
	EXTENDED_GROSS_AMOUNT FLOAT,
	GROSS_DEVELOPMENT_VALUE FLOAT,
	GROSS_DEVELOPMENT_VALUE_GROSS_LOAN_GREATER_NOTE VARCHAR(16777216),
	ASSET_VALUE_DAY_NET_ADVANCE_GREATER_NOTE VARCHAR(16777216),
	primary key (ID)
);
create or replace TABLE RAW_DRAWDOWN_EVENTS (
	ID NUMBER(38,0) NOT NULL,
	EVENT_DATE DATE NOT NULL,
	FINANCIAL_DATE DATE,
	DRAWDOWN_ID NUMBER(38,0),
	EVENT_TYPE_ID NUMBER(38,0),
	EVENT_STATUS_ID NUMBER(38,0),
	AMOUNT FLOAT NOT NULL,
	VARIABLE_RATE_SOURCE_ID NUMBER(38,0),
	ACCRUED_AMOUNT FLOAT,
	NOTE VARCHAR(16777216),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	END_DATE DATE,
	AMOUNT_OF_LOAN_IN_DEFAULT FLOAT,
	primary key (ID)
);
create or replace TABLE RAW_DRAWDOWN_EVENT_AMOUNT_TYPE (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DRAWDOWN_EVENT_STATUS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DRAWDOWN_EVENT_TYPE (
	ID NUMBER(38,0) NOT NULL,
	DRAWDOWN_EVENT_AMOUNT_TYPE_ID NUMBER(38,0),
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	ENABLED_TO_SCHEDULE_BEFORE NUMBER(38,0) NOT NULL DEFAULT 1,
	primary key (ID)
);
create or replace TABLE RAW_DRAWDOWN_FIELDS_APPROVAL (
	ID NUMBER(38,0) NOT NULL,
	FIELD_NAME VARCHAR(255),
	IS_APPROVED NUMBER(38,0) NOT NULL DEFAULT 0,
	APPROVED_BY NUMBER(38,0),
	DRAWDOWN_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_DRAWDOWN_STATUS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_EMAIL_CODE_AUTHENTICATION (
	ID NUMBER(38,0) NOT NULL,
	USER_ID NUMBER(38,0),
	CODE VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL,
	EXPIRES_AT TIMESTAMP_NTZ(9) NOT NULL,
	primary key (ID)
);
create or replace TABLE RAW_EXIT_FEE_TIERS (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	TERM_MONTH NUMBER(38,0),
	FEE_PERCENT NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_FAILED_JOBS (
	ID NUMBER(38,0) NOT NULL,
	UUID VARCHAR(255),
	CONNECTION VARCHAR(16777216),
	QUEUE VARCHAR(16777216),
	PAYLOAD VARCHAR(16777215),
	EXCEPTION VARCHAR(16777215),
	FAILED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	primary key (ID)
);
create or replace TABLE RAW_FEES (
	ID NUMBER(38,0) NOT NULL,
	FEE_STATUS_ID NUMBER(38,0),
	INVOICE_PAID_DATE DATE,
	DATE DATE,
	FEE_TYPE_ID NUMBER(38,0),
	SERVICE_PROVIDER_ID NUMBER(38,0),
	FEE_AMOUNT FLOAT,
	FEE_AMOUNT_PERC FLOAT,
	CURRENCY_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	FEE_INTEREST NUMBER(38,0),
	GENERATE_INVOICE FLOAT DEFAULT 1,
	INVOICE_DUE_DATE DATE,
	NOTES VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	ADDED_TO_LOAN NUMBER(38,0) NOT NULL DEFAULT 0,
	START_DATE DATE,
	END_DATE DATE,
	BROKER_AGENT_ID NUMBER(38,0),
	RETAINED_FROM_NET_ADVANCE NUMBER(38,0) NOT NULL DEFAULT 0,
	COMMITMENT_FEE_REFUND_AMOUNT NUMBER(10,2),
	COMMITMENT_FEE_REFUND_DATE DATE,
	COMMITMENT_FEE_REFUND_PERIOD NUMBER(38,0),
	QUOTED_DATE DATE,
	QUOTE_CONFIRMED_DATE DATE,
	UNDERTAKING_CONFIRMED_DATE DATE,
	primary key (ID)
);
create or replace TABLE RAW_FEE_OPTIONS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_FEE_STATUS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_FEE_TYPE (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DEFAULT_VALUE_FLAT FLOAT,
	DEFAULT_VALUE_PERC FLOAT,
	NOT_DELETABLE RAW_NUMBER(38,0),
	primary key (ID)
);
create or replace TABLE RAW_FILES (
	ID NUMBER(38,0) NOT NULL,
	DEAL_DOCUMENT_CATEGORY_ID NUMBER(38,0),
	DIRECTORY VARCHAR(255),
	FILENAME VARCHAR(255),
	ORIGINAL_FILENAME VARCHAR(255),
	MIME VARCHAR(255),
	SIZE NUMBER(38,0) NOT NULL,
	USER_ID NUMBER(38,0),
	DOCUMENT_FOLDER VARCHAR(1000),
	SHAREPOINT_PATH VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	SHAREPOINT_UNIQUE_ID VARCHAR(255),
	primary key (ID)
);
create or replace TABLE RAW_FORM_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_GUARANTORS (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	CLIENT_COMPANY_ID NUMBER(38,0),
	CLIENT_GROUP_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_INTEREST_CALCULATION_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	FORMULA VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_INTEREST_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_INTRODUCERS (
	ID NUMBER(38,0) NOT NULL,
	COMPANY VARCHAR(255),
	CONTACT VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	INTRODUCER_TYPE_ID NUMBER(38,0),
	primary key (ID)
);
create or replace TABLE RAW_INTRODUCER_TYPE (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_LENDERS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_LENDER_OPERATIONAL_TEAM_ADMIN (
	ID NUMBER(38,0) NOT NULL,
	USER_ID NUMBER(38,0),
	LENDER_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_LINKED_DEALS (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	LINKED_DEAL_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	CROSS_COLLATERALIZED NUMBER(38,0) NOT NULL DEFAULT 0,
	primary key (ID)
);
create or replace TABLE RAW_LOAN_ADMINISTRATORS (
	ID NUMBER(38,0) NOT NULL,
	DEAL_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	CLIENT_COMPANY_ID NUMBER(38,0),
	CLIENT_GROUP_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_LOAN_CALCULATION_METHOD (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_LOAN_CUSTOM_FORMS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	FORM_DATA VARCHAR(16777215),
	CREATED_BY NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	REFERENCE VARCHAR(16777216),
	FORM_TYPE_ID NUMBER(38,0),
	PAYMENT_REQUIRED NUMBER(38,0) NOT NULL DEFAULT 0,
	PAYMENT_FEE FLOAT NOT NULL,
	E_SIGN_REQUIRED FLOAT NOT NULL DEFAULT 0,
	primary key (ID)
);
create or replace TABLE RAW_MARGIN_OVERRIDE (
	ID NUMBER(38,0) NOT NULL,
	DRAWDOWN_ID NUMBER(38,0),
	FROM_DATE TIMESTAMP_NTZ(9) NOT NULL,
	TO_DATE TIMESTAMP_NTZ(9) NOT NULL,
	RATE FLOAT NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_MARITAL_STATUSES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_MARKETING_SOURCES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_MIGRATIONS (
	ID NUMBER(38,0) NOT NULL,
	MIGRATION VARCHAR(255),
	BATCH NUMBER(38,0) NOT NULL,
	primary key (ID)
);
create or replace TABLE RAW_MODEL_HAS_PERMISSIONS (
	PERMISSION_ID NUMBER(38,0) NOT NULL,
	MODEL_TYPE VARCHAR(255) NOT NULL,
	MODEL_ID NUMBER(38,0) NOT NULL,
	primary key (PERMISSION_ID, MODEL_ID, MODEL_TYPE)
);
create or replace TABLE RAW_MODEL_HAS_ROLES (
	ROLE_ID NUMBER(38,0) NOT NULL,
	MODEL_TYPE VARCHAR(255) NOT NULL,
	MODEL_ID NUMBER(38,0) NOT NULL,
	primary key (ROLE_ID, MODEL_ID, MODEL_TYPE)
);
create or replace TABLE RAW_NAME_TITLES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_NOTES (
	ID NUMBER(38,0) NOT NULL,
	NOTE VARCHAR(16777216),
	CREATED_BY NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_NOTIFICATION (
	ID NUMBER(38,0) NOT NULL,
	DEAL_NOTIFICATION_RULE_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	DRAWDOWN_ID NUMBER(38,0),
	DRAWDOWN_EVENT_TYPE_ID NUMBER(38,0),
	FILE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_NOTIFICATION_RECIPIENTS (
	ID NUMBER(38,0) NOT NULL,
	NOTIFICATION_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	USED_EMAIL_ADDRESS NUMBER(38,0),
	SUBJECT VARCHAR(255),
	BODY VARCHAR(16777216),
	SENT NUMBER(38,0) NOT NULL DEFAULT 0,
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_NOTIFICATION_RULES (
	ID NUMBER(38,0) NOT NULL,
	NOTIFICATION_TEMPLATE_ID NUMBER(38,0),
	DRAWDOWN_EVENT_TYPE_ID NUMBER(38,0),
	SCHEDULED_FOR NUMBER(38,0),
	INTERVAL_TYPE VARCHAR(255),
	SUBJECT_OVERRIDE VARCHAR(255),
	BODY_OVERRIDE VARCHAR(16777216),
	FILE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_NOTIFICATION_TEMPLATES (
	ID NUMBER(38,0) NOT NULL,
	DOC_REFERENCE VARCHAR(255),
	SUBJECT VARCHAR(255),
	BODY VARCHAR(16777216),
	FILE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ORDERS (
	ID NUMBER(38,0) NOT NULL,
	CLIENT_FORM_ID NUMBER(38,0),
	USER_ID NUMBER(38,0),
	ORDER_STATUS_ID NUMBER(38,0),
	PAYMENT_ID NUMBER(38,0),
	NET_TOTAL FLOAT NOT NULL DEFAULT 0,
	GROSS_TOTAL FLOAT NOT NULL DEFAULT 0,
	VAT_RATE FLOAT NOT NULL DEFAULT 1,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ORDER_STATUSES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_OWNERSHIP_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_PASSWORD_RESETS (
	EMAIL VARCHAR(255),
	TOKEN VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE RAW_PAYMENTS (
	ID NUMBER(38,0) NOT NULL,
	BASE_COST NUMBER(38,0),
	VAT_RATE FLOAT NOT NULL,
	GROSS_TOTAL FLOAT NOT NULL,
	CHARGE_OUTCOME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_PAYMENT_ATTEMPTS (
	ID NUMBER(38,0) NOT NULL,
	PAYMENT_ID NUMBER(38,0),
	AMOUNT NUMBER(10,2) NOT NULL DEFAULT 0,
	STATUS NUMBER(38,0) NOT NULL,
	ERROR_MESSAGE VARCHAR(255),
	PAYMENT_METHOD_ID NUMBER(38,0),
	PAYMENT_INTENT_ID VARCHAR(255),
	PAYMENT_REFERENCE VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_PAYMENT_PROVIDERS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	IS_DEFAULT NUMBER(38,0) NOT NULL DEFAULT 0,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_PERMISSIONS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	GUARD_NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_PERSONAL_ACCESS_TOKENS (
	ID NUMBER(38,0) NOT NULL,
	TOKENABLE_TYPE VARCHAR(255),
	TOKENABLE_ID NUMBER(38,0),
	NAME VARCHAR(255),
	TOKEN VARCHAR(64),
	ABILITIES VARCHAR(16777216),
	LAST_USED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_PROVIDER_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DETAILS VARCHAR(16777216),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_PURPOSE_CREDIT_TYPES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_QUOTES (
	ID NUMBER(38,0) NOT NULL,
	DRAWDOWN_PROFILE_ID NUMBER(38,0),
	QUOTES_STATUS_ID NUMBER(38,0),
	DEAL_ID NUMBER(38,0),
	FILE_ID NUMBER(38,0),
	NOTES VARCHAR(16777216),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_QUOTES_RECIPIENTS (
	ID NUMBER(38,0) NOT NULL,
	QUOTE_ID NUMBER(38,0),
	CLIENT_INDIVIDUAL_ID NUMBER(38,0),
	USED_EMAIL_ADDRESS VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_QUOTES_STATUS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_QUOTE_NOTE (
	ID NUMBER(38,0) NOT NULL,
	QUOTE_ID NUMBER(38,0),
	NOTES VARCHAR(16777216),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ROLES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	GUARD_NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_ROLE_HAS_PERMISSIONS (
	PERMISSION_ID NUMBER(38,0) NOT NULL,
	ROLE_ID NUMBER(38,0) NOT NULL,
	primary key (PERMISSION_ID, ROLE_ID)
);
create or replace TABLE RAW_SCHEDULED_NOTIFICATIONS (
	ID NUMBER(38,0) NOT NULL,
	DEAL_NOTIFICATION_RULE_ID NUMBER(38,0),
	SCHEDULED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ENABLED NUMBER(38,0),
	ENABLED_BY_USER_ID NUMBER(38,0),
	SENT NUMBER(38,0) NOT NULL DEFAULT 0,
	DATETIME_SENT TIMESTAMP_NTZ(9),
	SUBJECT_SENT VARCHAR(255),
	BODY_SENT VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DELETED_AT TIMESTAMP_NTZ(9),
	DRAWDOWN_EVENT_ID NUMBER(38,0),
	primary key (ID)
);
create or replace TABLE RAW_SERVICE_PROVIDERS (
	ID NUMBER(38,0) NOT NULL,
	PROVIDER_TYPE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	FORENAME VARCHAR(255),
	SURNAME VARCHAR(255),
	COMPANY VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(255),
	ENGAGEMENT_LETTER DATE,
	primary key (ID)
);
create or replace TABLE RAW_SHAREPOINT_UPDATES_TIMESTAMPS (
	ID NUMBER(38,0) NOT NULL,
	LAST_UPDATE TIMESTAMP_NTZ(9) NOT NULL,
	CHANGE_TOKEN VARCHAR(255),
	primary key (ID)
);
create or replace TABLE RAW_SYSTEMS_DEAL_SETTING (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	ORDER_ID NUMBER(38,0),
	SYSTEMS_DEAL_SETTING_GROUP_ID NUMBER(38,0),
	STATUS NUMBER(38,0) NOT NULL DEFAULT 0,
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_SYSTEMS_DEAL_SETTING_GROUPS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	ORDER_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_TASK (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	ORDER_ID NUMBER(38,0),
	TASK_GROUP_ID NUMBER(38,0),
	AUTO_ASSIGN_TO_CASE_OWNER NUMBER(38,0) NOT NULL DEFAULT 0,
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_TASK_GROUP (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	ORDER_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_USERS (
	ID NUMBER(38,0) NOT NULL,
	TYPE_ID NUMBER(38,0),
	COMPANY_ID NUMBER(38,0),
	AVATAR_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(255),
	EMAIL_VERIFIED_AT TIMESTAMP_NTZ(9),
	CHANGE_PASSWORD_DATETIME TIMESTAMP_NTZ(9),
	REMEMBER_TOKEN VARCHAR(100),
	VERIFICATION_TOKEN VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	STRIPE_ID VARCHAR(255),
	PM_TYPE VARCHAR(255),
	PM_LAST_FOUR VARCHAR(4),
	TRIAL_ENDS_AT TIMESTAMP_NTZ(9),
	IS_ACTIVE NUMBER(38,0) NOT NULL DEFAULT 1,
	DELETED_AT TIMESTAMP_NTZ(9),
	PAYMENT_PROVIDER_ID NUMBER(38,0),
	FILE_ID NUMBER(38,0),
	primary key (ID)
);
create or replace TABLE RAW_USER_TYPES (
	ID NUMBER(38,0) NOT NULL,
	ROLE_ID NUMBER(38,0),
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	IS_ADMIN NUMBER(38,0) NOT NULL DEFAULT 0,
	primary key (ID)
);
create or replace TABLE RAW_USE_TYPE (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_VALUATIONS (
	ID NUMBER(38,0) NOT NULL,
	ASSET_ID NUMBER(38,0),
	SERVICE_PROVIDER_ID NUMBER(38,0),
	DOCUMENT_ID NUMBER(38,0),
	CURRENCY_ID NUMBER(38,0),
	FEE_OPTION_ID NUMBER(38,0),
	VALUATION_STATUS_ID NUMBER(38,0),
	REPORT_RECEIVED_DATE DATE,
	DATE_EXPECTED DATE,
	INVOICE_DUE_DATE DATE,
	FEE_AMOUNT FLOAT,
	FILE_ID NUMBER(38,0),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	REPORT_REQUESTED_DATE DATE,
	primary key (ID)
);
create or replace TABLE RAW_VALUATION_STATUSES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	DELETED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_VARIABLE_RATES (
	ID NUMBER(38,0) NOT NULL,
	VARIABLE_RATE_SOURCE_ID NUMBER(38,0),
	PARENT_ID NUMBER(38,0),
	RATE FLOAT NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_VARIABLE_RATES_HISTORY (
	ID NUMBER(38,0) NOT NULL,
	DATE DATE NOT NULL,
	VARIABLE_RATE_SOURCE_ID NUMBER(38,0),
	RATE FLOAT NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_VARIABLE_RATES_HISTORY_COPY1 (
	ID NUMBER(38,0) NOT NULL,
	DATE DATE NOT NULL,
	VARIABLE_RATE_SOURCE_ID NUMBER(38,0),
	RATE FLOAT NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_VARIABLE_RATE_SETTINGS (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	VALUE FLOAT NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE RAW_VARIABLE_RATE_SOURCES (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
