CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_attribute_values ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_asset_client_individuals ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_document_categories_data ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_purpose_credit_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_valuation_statuses ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_sharepoint_updates_timestamps ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_name_titles ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_scheduled_notifications ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_attribute_groups ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_guarantors ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_drawdown_fields_approval ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_broker_agents ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_fees ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_attribute_entities ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_notification_rules ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_systems_deal_setting ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_orders ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_payment_attempts ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_users ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_task ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_broker_agent_deals ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_asset_addresses ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_lender_operational_team_admin ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_group_clients ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_notification ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_asset_insurances ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_exit_fee_tiers ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_variable_rate_settings ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_variable_rates ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_user_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_asset_client_companies ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_lenders ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_drawdowns ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_companies ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_document_categories ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_loan_administrators ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_bank_details ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_use_type ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_drawdown_event_status ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_charges ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_variable_rates_history ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_variable_rates_history_copy1 ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_activity_log ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_charge_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_linked_deals ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_groups ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_task_group ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_attributes ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_individuals ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_quotes_status ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_notes ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_role_has_permissions ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_audit ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_payments ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_form_status ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_loan_calculation_method ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_settings ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_personal_access_tokens ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_statuses ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_files ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_asset_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_service_providers ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_form_attachments ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deals ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_asset_insurance_notes ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_interest_calculation_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_brokers ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_document_risk ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_systems_deal_setting_groups ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_form_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_permissions ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_notification_recipients ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_documents ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_interest_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_migrations ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_variable_rate_sources ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_introducers ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_activities ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_drawdown_event_type ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_aborted_reasons ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_documents ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_drawdown_events ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_drawdown_status ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_company_notes ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_broker_notes ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_introducers ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_assets ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_task ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_attribute_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_addresses ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_notification_rules_recipients ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_email_code_authentication ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_loan_custom_forms ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_failed_jobs ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_marketing_sources ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_notes ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_order_statuses ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_delegated_owners ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_ownership_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_introducer_type ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_quotes ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_fee_status ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_individual_notes ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_quotes_recipients ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_currencies ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_borrowers ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_document_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_marital_statuses ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_notification_templates ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_notification_rules ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_rate_floors ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_valuations ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_drawdown_event_amount_type ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_model_has_permissions ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_companies ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_provider_types ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_roles ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_task_group ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_ccr_reports ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_quote_note ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_fee_options ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_broker_agent_notes ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_forms ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_margin_override ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_client_company_clients ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_fee_type ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_payment_providers ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_model_has_roles ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_deal_setting_groups ( RAW_DATA VARIANT );
CREATE 
  OR REPLACE TABLE RAW_JSON_DATA_password_resets ( RAW_DATA VARIANT );
